### PR TITLE
solution to make network call on main thread

### PR DESCRIPTION
**Pull request by maifeeulasad**
Hello, I've added a solution that lets you make any network call on the main thread, that's how API calls during scene changing works. 

Thanks. Let me know if there are any issues. I guess I've properly cited the sources too.

Closes https://github.com/proyecto26/RestClient/issues/179
Closes https://github.com/proyecto26/RestClient/issues/8
Maybe this also helps https://github.com/proyecto26/RestClient/issues/154

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hello mate, thanks for your contribution! <3

**Comment by maifeeulasad** [comment]
Hello @jdnichollsc, It's an honor to be part of this great work and community.

**Comment by jdnichollsc** [comment]
@maifeeulasad hey mate, do you want to be a maintainer of this lib? <3

**Comment by maifeeulasad** [comment]
I'm not sure what I'll be able to do, but this can be an interesting journey and a 🎁 . 
Looking forward to it.  💌

**Comment by jdnichollsc** [comment]
let me send you an invite, thanks for your help! 💯

**Pull request merged**
