### PR TITLE
Unity Package Manager

### PR DESCRIPTION
**Pull request by benukhanov**
Hey!

I worked two hours to add support for the Unity package manager. You have to merge develop into master for GitHub Actions to create an "upm" branch for the package manager. I have added installation instructions for you to read.

See how this works with [forked repository](https://github.com/benukhanov/RestClient/tree/feature/unity-package#installation-).

Enjoy. :heart:

### CODE REVIEW

**Comment by benukhanov** [comment]
@jdnichollsc Let me know if you have any questions.

**Comment by jdnichollsc** [comment]
Hello Ben, thanks for your contribution! <3

What are the new changes? I can see a lot of modifications (78 files changed).

Thanks for your help!

**Comment by benukhanov** [comment]
> Hello Ben, thanks for your contribution! <3
> 
> What are the new changes? I can see a lot of modifications (78 files changed).
> 
> Thanks for your help!

The "Add rest client files" commit is the files imported from your Unity package file, so you see a lot of changes.

Other changes:

- Updated readme
- Added asmdef file (Unity's dll file)
- New folder src/Unity/Package (The files inside Package folder will be visible in "upm" branch, it's for Unity)
- Deleted old and added new package.json (It's for Unity)
- Added .github/workflows/main.yml

That's it.

FYI - I tested in Unity and everything is works.

**Comment by jdnichollsc** [comment]
Can we support upm branch without affecting the structure of the project? Right now we have a pipeline from Azure DevOps and other configurations with the current path

**Comment by benukhanov** [comment]
> Can we support upm branch without affecting the structure of the project? Right now we have a pipeline from Azure DevOps and other configurations with the current path

Yes, then we don't need the upm branch. Good to do:

https://github.com/proyecto26/RestClient.git?path=src/Unity/Package#develop
or
https://github.com/proyecto26/RestClient.git?path=src/Unity/Package#master

Whatever you decide to put in the readme (let me know).

Cool?

**Comment by benukhanov** [comment]
rest-client-package

**Comment by benukhanov** [comment]
@jdnichollsc Removed main.yml and updated url to:

https://github.com/proyecto26/RestClient.git?path=src/Unity/Package#develop

**Comment by jdnichollsc** [comment]
I mean, we have the source code in this path:
- https://github.com/benukhanov/RestClient/tree/feature/unity-package/src/Proyecto26.RestClient

And you're duplicating the files here:
- https://github.com/benukhanov/RestClient/tree/feature/unity-package/src/Unity/Package/Runtime/Proyecto26.RestClient

How can we avoid it? :)

**Comment by benukhanov** [comment]
> I mean, we have the source code in this path:
> 
> * https://github.com/benukhanov/RestClient/tree/feature/unity-package/src/Proyecto26.RestClient
> 
> And you're duplicating the files here:
> 
> * https://github.com/benukhanov/RestClient/tree/feature/unity-package/src/Unity/Package/Runtime/Proyecto26.RestClient
> 
> How can we avoid it? :)

We can't. We should have Unity's metadata files generated from csharp files. We also cannot have two dlls (RSG.Promise.dll and Proyecto26.RestClient.dll).. lol. I tried to put these files in one Unity package:

- https://github.com/benukhanov/RestClient/tree/feature/unity-package/demo/Assets/Packages

and Unity doesn't allow it, throws an error. Maybe Unity will get better in the future. :smile: 

---

To be honest, we don't need a csharp project for the RestClient, because today we don't need NuGet (we have a Unity package manager). And we don't need to use the Unity package file to import the source files (because we don't need them in the Assets folder, as for this we have a new Unity package manager). The Unity package file is for older versions of Unity. Also your UnityEngine.dll is an old version and the demo folder is out of date (when you open this demo folder with a newer version of Unity you get warnings / errors).

The best solution is to make the new src/Unity/Package folder as the new /src folder to avoid code duplication.

**Comment by benukhanov** [comment]
Here's an example of what your RestClient repository should look like:

https://github.com/endel/NativeWebSocket

I also made this repository to support Unity package manager. I need rest client and websockets for my [maple-fighters](https://github.com/benukhanov/maple-fighters) project. :smile:

**Comment by benukhanov** [comment]
We can also generate meta files here: https://github.com/benukhanov/RestClient/tree/feature/unity-package/src/Proyecto26.RestClient and update package.json, but then it is strange to see meta files in csharp project because the meta files are only for the Unity project. Let's say you add a new Sample.cs, so you need Sample.cs.meta, if you don't add the .meta file then Unity will throw an error and the package will be broken.

**Comment by benukhanov** [comment]
@jdnichollsc Hey! Please let me know if you'll merge this PR, if not then let's close it.

**Comment by jdnichollsc** [comment]
Sorry mate, I'm participating in the Global Game Jam, so I have been busy these days, let me review your changes as soon as possible

**Comment by benukhanov** [comment]
> Sorry mate, I'm participating in the Global Game Jam, so I have been busy these days, let me review your changes as soon as possible

Gotcha, take your time, everything is fine. I wanted to make sure it's on your to-do list.

Good luck in the GGJ :)

**Comment by benukhanov** [comment]
@jdnichollsc How's going? :)

**Comment by Eomono** [comment]
@benukhanov Hey Ben! This is exactly what I was looking for, thank you for setting it up. Would you mind if I use your branch as a dependency until this request gets resolved?  Cheers!

**Comment by benukhanov** [comment]
> @benukhanov Hey Ben! This is exactly what I was looking for, thank you for setting it up. Would you mind if I use your branch as a dependency until this request gets resolved? Cheers!

Hi, of course, but keep in mind that the branch is not updated with the latest commits. I think it's better to do something like what I did for my game [here](https://github.com/benukhanov/maple-fighters/tree/develop/src/maple-fighters/Packages/com.proyecto26.restclient).

What I did: I manually added the rest-client as a package instead of storing it in the Assets folder.

---

When this PR is closed, I'll delete the forked repository.

**Comment by Eomono** [comment]
@benukhanov Ah I see! Oh well, I guess I will do that instead. Thank you so much for the advice!
Cheers!

**Comment by jdnichollsc** [comment]
Hello folks, sorry for the delay
We don't want to include source files of [C-Sharp-Promise](https://github.com/Real-Serious-Games/C-Sharp-Promise) library in this repository, how can you avoid that? :)

**Comment by jdnichollsc** [comment]
Also, if we need to change the structure of the project, can we use another branch to support Unity Package Manager?

**Comment by tonygiang** [comment]
> Hello folks, sorry for the delay
> We don't want to include source files of [C-Sharp-Promise](https://github.com/Real-Serious-Games/C-Sharp-Promise) library in this repository, how can you avoid that? :)

Ideally, the source files you depend on would have to be its own upm package, then you can add it to your package manifest as a dependency which will then be resolved by Unity. [More information](https://docs.unity3d.com/Manual/upm-dependencies.html).

A quick search show a fork of C-Sharp-Promise with UPM compatibility [here](https://github.com/RoryDungan/C-Sharp-Promise-UPM).

**Comment by benukhanov** [comment]
> Hello folks, sorry for the delay
> We don't want to include source files of [C-Sharp-Promise](https://github.com/Real-Serious-Games/C-Sharp-Promise) library in this repository, how can you avoid that? :)

Hi, I was very busy last two weeks. I'll get back to you ASAP.

**Comment by jdnichollsc** [comment]
No problem, I understand 😅

**Comment by tonygiang** [comment]
Hey folks, while the OP of this PR is still working out a solution, you can grab a UPM-compatible version of RestClient on my (temporary) fork here:

https://github.com/tonygiang/RestClient

**Comment by benukhanov** [comment]
> Hello folks, sorry for the delay
> We don't want to include source files of [C-Sharp-Promise](https://github.com/Real-Serious-Games/C-Sharp-Promise) library in this repository, how can you avoid that? :)

Thanks to @tonygiang's suggestion, I removed the RSG.Promise library from the Unity folder. Now it only depends on the [C-Sharp-Promise-UPM](https://github.com/RoryDungan/C-Sharp-Promise-UPM) repository.

So when you open the Unity Package Manager window you need to add the RSG.Promise package and then RestClient, otherwise it won't work.

> Also, if we need to change the structure of the project, can we use another branch to support Unity Package Manager?

We need to change the project structure because we don't need a C# project separated from the Unity project. There is no reason to use a different branch.

**Comment by benukhanov** [comment]
@jdnichollsc you can also use @tonygiang forked repository to add UPM support. Be aware that it uses files that shouldn't be part of this package (C# project source files, for example * .csproj).

If you prefer his solution, then let's close this PR and he'll open his PR.

**Comment by tonygiang** [comment]
I removed the csproj file (and its meta) from my fork.

**Comment by benukhanov** [comment]
@jdnichollsc Hi, let's close this PR and use @tonygiang solution?

**Comment by benukhanov** [comment]
Here's all my changes: [RestClient-feature-unity-package.zip](https://github.com/proyecto26/RestClient/files/6699629/RestClient-feature-unity-package.zip) (feature/unity-package branch)

Whatever you decide to use my solution so go for it. I think it's better to use tonygiang's solution. :smile:

**Comment by jdnichollsc** [comment]
Hello folks, thanks for your collaboration!

We're using a GitHub action now instead here: https://github.com/proyecto26/RestClient/pull/198/files

Please check the `upm` branch and let me know!

Happy holidays <3

**Pull request closed without merging**
