### PR TITLE
Switch RSG to ProtoPromise.

### LINKED ISSUE #107: Promise abort enhancement
Iv been using the library for last few weeks and it has worked for me very well, however there is one thing that I find abit inconvenient - aborting requests. 

I set up a repository class for my rest api:

    public class LadderRepository : MonoBehaviour {

        private static string ladderFinalUrl = "ladder";

        private readonly IList<RequestHelper> requests = new List<RequestHelper>();

        private void Awake() {
            InitUrls();
        }

        private void InitUrls() {
         .....
        }

        public IPromise<LadderResponse> FetchLadder() {
            var requestHelper = ComposeRequest(ladderFinalUrl);
            return RestClient.Get<LadderResponse>(requestHelper);
        }

}

Basically I expose `IPromises `for other game objects that want to communicate with the api, now my problem is aborting individual `IPromises`. 

Ideally Id like to just call a method `Abort ` on given `IPromise` to cancel given api call. I am used to abort things like this from rxjava - disposing an observable whenever I feel like. 

Maybe I am missing something but right now Id have to expose given `RequestHelpers` to achieve what I want, which doesnt seem to be so clean.  What do you think about it?

### LINKED ISSUE #216: Update promises to be awaitable using `async`/`await`
Promises are so ugly, especially when you have to chain multiple `.Then()` blocks. So I tried to `await` the promise instead, but it won't compile because they're not awaitable.

Now this might be just a misunderstanding of C# promises, coming from JavaScript ESNext, but isn't `async`/`await` basically the same thing as promises, but with much cleaner and nicer syntax?

As in, doesn't this code

```cs
RestClient.Get("/api/something")
.Then(response => {
    Debug.Log(response.Text);
});
```

do the exact same thing as this one?

```cs
var response = await RestClient.Get("/api/something");
Debug.Log(response.Text);
```

Or at least it would if the promise could be awaited. Which would be awesome!

### PR DESCRIPTION
**Pull request by timcassell**
Resolves #216 and resolves #107.

@jdnichollsc I am not sure how your package build system works, so I only updated the src and demo. Feel free to edit my branch or give feedback for me to change other parts.

Also, since this will be a breaking change, the release version should probably be updated to 3.0.0 if this is accepted.

### CODE REVIEW

**Comment by timcassell** [comment]
@jdnichollsc I just updated this PR with the latest version of ProtoPromise, and I re-implemented the Promise requests more efficiently. PTAL

**Comment by kapyar** [comment]
Hi @timcassell do you have a unity package for your implementation? Tried to replace folders in the RestClient folder and got errors in the editor.

**Comment by timcassell** [comment]
@kapyar What errors? Do you have ProtoPromise installed?

**Comment by HajiyevEl** [comment]
@timcassell Hi! Thanks for your work. How can i install this branch?

**Comment by timcassell** [comment]
@HajiyevEl First, install ProtoPromise ([instructions](https://github.com/timcassell/ProtoPromise#package-installation)), then install this branch via git url in the Package Manager.
```
https://github.com/timcassell/RestClient.git?path=src/Proyecto26.RestClient#protopromise
```
@kapyar I also fixed your issue by adding the assembly reference.

**Comment by timcassell** [comment]
Closed because this project is apparently dead, and I have removed support for .Net 3.5 in ProtoPromise. If there is any interest from the maintainers to update this project, I will be happy to help.

**Pull request closed without merging**
