### PR TITLE
Removing Depricated APIs

### PR DESCRIPTION
**Pull request by Drazail**
# Removed depricated APIs
 - `UnityWebRequest.result.isNetworkError` 
 - `UnityWebRequest.result.isHttpError`
# Replaced with 
- `UnityWebRequest.Result.ConnectionError` 
- `UnityWebRequest.Result.ProtocolError`

### CODE REVIEW

**Comment by Drazail** [comment]
Travis seems to build using an older versions of unity (ie: 2019.x), these changes aren't necessary unless you decide to support unity 2020+.

**Comment by jdnichollsc** [comment]
Can you use compilations conditionals to support previous versions too? e.g: https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/Helpers/RequestHelper.cs#L203

**Comment by Drazail** [comment]
> Can you use compilations conditionals to support previous versions too? e.g: https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/Helpers/RequestHelper.cs#L203

done

**Comment by jdnichollsc** [comment]
Thanks for your help mate!

**Pull request merged**
